name: hid
description: A multi-platform plugin which allows an application to interface with USB HID-Class devices on Windows, Android, and macOS.
version: 0.1.0
repository: https://github.com/rustui/hid/tree/main/hid

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hid_platform_interface: ^0.0.7
  hid_windows: ^0.0.7
  hid_macos: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
      platforms:
        windows:
          default_package: hid_windows
        macos:
          default_package: hid_macos
